name: CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      jdk:
        default: 8
        type: string
      os:
        default: ubuntu-latest
        type: string
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-java-${{ inputs.jdk }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Fetch container
        run: docker pull grokzen/redis-cluster:6.2.0
      - name: Run redis test cluster
        run: docker run -d -e 'IP=127.0.0.1' -e 'STANDALONE=true' -e 'SENTINEL=true' -p '7000-7007:7000-7007' -p '5000-5002:5000-5002' grokzen/redis-cluster:6.2.0
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B
      - name: Publish Unit Test Results
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/surefire-reports/*.xml'
          report_individual_runs: true
